name: Deploy Golang project to function app with a Windows environment

on: [push]

env:
  AZURE_FUNCTIONAPP_NAME: winefamilies
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: "Checkout GitHub action"
        uses: actions/checkout@v2

      - name: Setup Golang ${{ env.GOLANG_VERSION }} Environment
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true
      - run: go version

      - name: "Build Project"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          go build -o handler main.go
          popd

      - name: "Run Azure Functions action"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/handler"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
